name: glogic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  float_column: ^4.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  smooth_page_indicator: ^2.0.1
  supabase_flutter: ^2.12.0
  zo_animated_border: ^1.0.6
  confetti: ^0.7.0
  animated_bottom_navigation_bar: ^1.4.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/detective.jpg
    - assets/images/giay.jpg
    - assets/frames/wood.jpg
    - assets/frames/Cu.jpg
    - assets/frames/silver.jpg
    - assets/frames/gold.jpg
